name: GitHub Classroom Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Autograding
    runs-on: ubuntu-latest
    outputs:
      details: ${{ steps.autograding.outputs.details }}
      points: ${{ steps.autograding.outputs.points }}
      finished_lab: ${{ env.FINISHED_LAB }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0
          platforms: riscv64

      - name: Cache Rust dep
        id: cache-rust
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rust-src, llvm-tools-preview
          target: riscv64gc-unknown-none-elf
          override: true

      - name: Install cargo-binutils
        if: steps.cache-rust.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-binutils

      - name: Build and Test
        run: make ci-test | tee qemu_run_output.txt

      - name: Prepare os-autograding
        run: |
          mkdir .github/classroom
          cp -r conf/autograding/* .github/classroom

      - name: os-autograding
        id: autograding
        uses: yfblock/os-autograding@master
        with:
          outputFile: qemu_run_output.txt
          scriptPath: .github/classroom

      - name: Export ENV
        id: export-env
        uses: krisalay/export-env@v1.0.0
        with:
          filename: .env

  deploy:
    name: Deploy to pages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: 'gh-pages'
      - name: Save Log File
        continue-on-error: true
        run: |
          mkdir autograding_logs
          cd autograding_logs
          if [  -f "../latest.json"  ]; then
              cp ../latest.json older.json
          else
              echo "{}" > older.json
          fi
          FILE_NAME=`date +%Y_%m_%d_%H_%M_%S`.txt
          echo -ne "${{ needs.test.outputs.details }}\n" > $FILE_NAME
          echo -ne "Points: ${{ needs.test.outputs.points }}" > $FILE_NAME
          cat older.json | jq ".${{ needs.test.outputs.finished_lab }} |= \"$FILE_NAME\"" > latest.json
          rm older.json
          echo -ne "# Got Points\n" > README.md
          echo "![Points bar](../../blob/gh-pages/points-badge.svg)" >> README.md
      - name: Make points svg
        uses: markpatterson27/points-bar@v1
        with:
          points: '${{ needs.test.outputs.points }}'
          path: 'autograding_logs/points-badge.svg'
          type: 'badge'
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: autograding_logs
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
